### ISSUE TITLE
Please release new version on npm

### ISSUE THREAD

**Issue by nylen** [wilberforce/pid-controller#4]
Hi @wilberforce - thanks for making this library available for Node.js.  I'm going to use it to make a kiln controller - the hardware is already done and now I just need to write a server program that lets you set temperature schedules and performs PID control to hit the desired temperatures.

It looks like after PR #2 was merged with an example in the readme file, the corresponding code was not pushed to npm.

As a result, running the example code in the readme against the latest released version (1.0.3) fails as follows:

```
$ node pid.js 
Output : 0 ; Temp : 9.5°c
Output : 0 ; Temp : 9°c
Output : 0 ; Temp : 8.5°c
Output : 0 ; Temp : 8°c
Output : 0 ; Temp : 7.5°c
Output : 0 ; Temp : 7°c
Output : 0 ; Temp : 6.5°c
Output : 0 ; Temp : 6°c
[...]
Output : 0 ; Temp : 1°c
Output : 0 ; Temp : 0.5°c
Output : 0 ; Temp : 0°c
Output : 0 ; Temp : -0.5°c
Output : 0 ; Temp : -1°c
Output : 0 ; Temp : -1.5°c
Output : 0 ; Temp : -2°c
Output : 0 ; Temp : -2.5°c
[...]
```

Can you please release the latest code on npm so that the example in the readme works as intended?

Note - if there are breaking changes in the new version, then the version number should be bumped to 2.0.0 to adhere to [semver](http://semver.org/), the npm versioning standard.

**Comment by wilberforce** [comment]
updated - 1.04
https://www.npmjs.com/package/pid-controller

**Comment by nylen** [comment]
Thanks!  The library is working quite well, here is an example from using the kiln controller:

![image](https://cloud.githubusercontent.com/assets/227022/15656526/f36326c0-266d-11e6-99bb-fce85717760b.png)

and here is the code so far (there are a few other repositories also):  https://github.com/redmountainmakers/kilntroller
