### ISSUE TITLE
Calculation of ITerm is incorrect

### ISSUE THREAD

**Issue by rgkarl** [wilberforce/pid-controller#5]
I'm getting wildly different output results after pulling the 1.0.4 version of PID.compute vs the 1.0.3 version. Comparing the two versions:

1.0.3:

![screen shot 2016-06-06 at 11 18 15 am](https://cloud.githubusercontent.com/assets/5489417/15829220/6d142f18-2bd8-11e6-9d10-2fe127f41e9d.png)

1.0.4:

![screen shot 2016-06-06 at 11 16 16 am](https://cloud.githubusercontent.com/assets/5489417/15829258/91564f78-2bd8-11e6-8a55-f1dde378a229.png)

The output saturator appears to be the root cause, and I am unable to explain why it was changed from this in 1.0.3:

`if(output > this.outMax) output = this.outMax;
      else if(output < this.outMin) output = this.outMin;`

to this in 1.0.4:

`if (output > this.outMax) {
            this.ITerm -= (output - this.outMax);
            output = this.outMax;
        }
        else if (output < this.outMin) {
            this.ITerm += (this.outMin - output);
            output = this.outMin;
        }`

**Comment by wilberforce** [comment]
@rgkarl 

I think it is related to this pull request:

https://github.com/wilberforce/pid-controller/pull/2

Do you have time to do a revert and a pull request, then I can merge that and bump to 1.5?

**Comment by wilberforce** [comment]
Hmm looking back at this, I'm not sure why line 69 and 73 were added..

https://github.com/br3ttb/Arduino-PID-Library/blob/master/PID_v1.cpp

They should be removed!

**Comment by wilberforce** [comment]
@rgkarl 
reverted in 
https://github.com/wilberforce/pid-controller/commit/f5d118cc0c260f7a2f9314c65e62a1616c307f29
